### ISSUE TITLE
Setup of platform gearbest is taking longer than 60 seconds.

### ISSUE THREAD

**Issue by Dmxsir** [HerrHofrat/hass_gearbest_sensor#1]
this is my setup, and its not creating the sensors.
```
sensor:
  - platform: gearbest
    items:
      - url: https://www.gearbest.com/cell-phones/pp_009284826952.html
        name: OnePlus 6t 1
      - url: https://www.gearbest.com/cell-phones/pp_009968241835.html
        name: OnePlus 6t 2
```
